### ISSUE TITLE
Cannot create Client

### ISSUE THREAD

**Issue by alosoft** [stanvanrooy/instauto#189]
**Describe the bug**
Am not able to create a client

**To Reproduce**
`>>> from instauto import api, bot
>>> client = api.client.ApiClient(username, password)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Alonso\AppData\Local\Programs\Python\Python39\lib\site-packages\instauto\api\client.py", line 65, in __init__
    self._user_agent = self._build_user_agent()
  File "C:\Users\Alonso\AppData\Local\Programs\Python\Python39\lib\site-packages\instauto\api\actions\request.py", line 157, in _build_user_agent
    s = f"Instagram {self.ig_profile.version} Android ({self.device_profile.android_sdk_version}/" \
AttributeError: 'str' object has no attribute 'version'
>>>`

But am able to get client this way

``>>> from instauto import api, bot
>>> bot = bot.Bot(username, password)
>>> client = bot._client
>>> client
<instauto.api.client.ApiClient object at 0x000001B4531E71C0>
>>>
`

**Setup**
Instauto version: 2.0.1

**Comment by stanvanrooy** [comment]
You should use `Client(user_name='username', password='password').

**Comment by alosoft** [comment]
> You should use `Client(user_name='username', password='password')`.

this gave me `got an unexpected keyword argument 'user_name'`

**Comment by stanvanrooy** [comment]
my bad, it's `username="your_username"`

**Comment by alosoft** [comment]
It's now working in version 2.0.2. Thanks
